# Schema for the configuration files of the popup_zip module.
popup_zip.settings:
  type: config_object
  label: 'popup_zip settings'
  mapping:
    example:
      type: string
      label: 'Example'

block.settings.popup_zip_questionsformpopupblock:
  type: block_settings
  label: 'QuestionsFormPopupBlock block'
  mapping:
    foo:
      type: string
      label: Foo
